services:
  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: ChatApp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
